### ISSUE TITLE
The source editor mentioned in the user guide (^S) doesn't open.

### ISSUE THREAD

**Issue by vadim-a-yegorov** [ktraunmueller/Compositor#598] opened 2024-05-01 22:19 UTC
Ctrl+S doesn't open the source editor.
Application menu entry "Toggle source editor" doesn't do anything, tried all possible files.

Problem appears only in 1.26 release.

**Comment by ktraunmueller** [comment] 2024-05-03 14:21
Vadim,

I cannot reproduce the issue, at least not with the information provided.

Here's what I tried:
- Create a new document (File / New / Standard Article)
- Press ^S

Observed:
- The source editor panel opens as expected:

<img width="1552" alt="Screenshot 2024-05-03 at 16 14 03" src="https://github.com/ktraunmueller/Compositor/assets/650763/ae9be9d9-9c3c-4af1-ab49-91f2a9aaf5ff">

Are you doing any additional steps?

Generally, when reporting problems, please provide:
- Accurate and descriptive title
- Clear and concise description of the problem
- Steps to reproduce
- Actual and expected outcome
- Context
  - Screenshots, videos (where it makes sense; optional)
- Product version
- OS version

**Comment by ktraunmueller** [comment] 2024-11-24 11:57
@vadim-a-yegorov The problem should be fixed in the upcoming 1.27 release, see #615

**Closed by ktraunmueller** 2024-11-24 11:57 UTC
