### ISSUE TITLE
It seems too many errors occurred while trying to typeset the document.

### ISSUE THREAD

**Issue by markmark1** [ktraunmueller/Compositor#143] opened 2017-08-17 14:11 UTC
It seems too many errors occurred while trying to typeset the document. unable to open any document  pls fix. it opens fine in Texpad and emacs and textmate why is it not opening in compositor????

**Comment by ktraunmueller** [comment] 2017-08-17 20:54
@markmark1 can you send me the file(s) that cause this error, please?

**Comment by markmark1** [comment] 2017-08-17 21:02
any file thats open...

**Comment by markmark1** [comment] 2017-08-17 21:02
https://github.com/dannywillems/tezos-white-paper check these for instance hth how to send to you? @ktraunmueller

**Comment by markmark1** [comment] 2017-08-17 21:03
ktraunmueller whats your email? is it ur user name at gmail

**Comment by ktraunmueller** [comment] 2017-08-17 21:04
@markmark1 The github URL is fine. You can also attach files to issues by simply dragging them on the comment field.

The problem is probably that this requires xelatex, but I'll have a a look. Thanks for reporting.

**Comment by ktraunmueller** [comment] 2017-09-19 21:27
**Closing** because it seems I forgot to attach the file

**Closed by ktraunmueller** 2017-09-19 21:27 UTC
Labels: bug
